### PR TITLE
fix: avoid re-mounting GCR volume with credentials

### LINKED ISSUE #2407: A vulnerabilityreport scan job cannot be started due to volume name duplicates in GKE
**What steps did you take and what happened:**
Hello everyone, I have faced the following issue: 

Trivy operator is unable to start a vulnerabilityreport scan job  in GKE for pods with more than 1 container, due to duplicate volume name gcrvol. However, it works fine with only one container in a pod. 

  > ReplicaSet":{"name":"redacted","namespace":"redacted"},"namespace":"redacted","name":"redacted","reconcileID":"419f6ca1-6242-4661-acf3-17827f37a045","error":"creating scan job failed: trivy-system/scan-vulnerabilityreport-6647b9b9bf: Job.batch "scan-vulnerabilityreport-6647b9b9bf" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "gcrvol", spec.template.spec.volumes[4].name: Duplicate value: "gcrvol", spec.template.spec.volumes[5].name: Duplicate value: "gcrvol", spec.template.spec.containers[1].volumeMounts[3].mountPath: Invalid value: "/cred": must be unique, spec.template.spec.containers[2].volumeMounts[3].mountPath: Invalid value: "/cred": must be unique, spec.template.spec.containers[2].volumeMounts[4].mountPath: Invalid value: "/cred": must be unique, spec.template.spec.containers[3].volumeMounts[3].mountPath: Invalid value: "/cred": must be unique, spec.template.spec.containers[3].volumeMounts[4].mountPath: Invalid value: "/cred": must be unique, spec.template.spec.containers[3].volumeMounts[5].mountPath: Invalid value: "/cred": must be unique]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}
  
**What did you expect to happen:**

In GKE cluster, a scan job successfully started for a pod with more then 1 container.

**Anything else you would like to add:**

A pod that could not be scanned contains 3 containers, one container image is fetched from docker hub and another 2 from are from private GCR. To fetch GCR there is **imagePullSecrets** secret mentioned in pod definition for these containers, to fetch an image from docker hub we do not mention anything in **imagePullSecrets**. 

However, in Trivy Operator settings we specified **privateRegistryScanSecretsNames** for images taken from docker hub, in order not to breach docker hub rate-limits. 

`privateRegistryScanSecretsNames: {"redacted": "dockerconfigjson-dockerhub-com"}
`

I tried to set the following parameter

`scanJob.useGCRServiceAccount: 'false' 
`

After which the scan job started, but I am getting another error 

> Registry flag error: the number of usernames and passwords must match. 

To address this, I tried to add gcr secret key to this variable

`privateRegistryScanSecretsNames: {"redacted": "dockerconfigjson-dockerhub-com,gcr-key"}
`

But it did not help, and the error above persists. 

Helm chart values are below

> ---
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: trivy-operator
      namespace: flux-system
    spec:
      chart:
        spec:
          version: 0.25.0
      values:
        nodeCollector:
          useNodeSelector: false
          excludeNodes: kubernetes.io/arch=amd64
    
        targetNamespaces: "redacted"
    
        operator:
          privateRegistryScanSecretsNames: {"redacted": "dockerconfigjson-dockerhub-com"}
          scanJobTimeout: 10m
          builtInTrivyServer: true
          scanJobsConcurrentLimit: 3
    
        trivy:
          mode: ClientServer
          severity: HIGH,CRITICAL
    
          server:
            resources:
              limits:
                memory: 2Gi
    
    

**Environment:**

- Trivy-Operator version: 0.23.0
- Kubernetes version: v1.30.5-gke.1713000
- OS: Container-Optimized OS 113

### PR DESCRIPTION
**Pull request by afdesk**
## Description

This PR adds a validation to ensure that a volume containing GCR credentials is present before proceeding.
If such a volume is already mounted, the logic prevents redundant re-mounting to avoid duplication and potential conflicts.

## Related issues
- Close #2407

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by afdesk** [comment]
@simar7 I remember you have a meticulous attitude toward testing, and I was thinking about how to add tests here.

A simple table-driven test for `createEnvAndVolumeForGcr` doesn’t make much sense in this context.

Once we resolve issues #2595 and #2769, we’ll be able to add a more meaningful test that covers multiple containers.

File: pkg/plugins/trivy/image.go [hunk 1]
```diff
@@ -775,6 +775,13 @@ func appendTrivyNonSSLEnv(config Config, image string, env []corev1.EnvVar) ([]c
 }
 
 func createEnvandVolumeForGcr(env *[]corev1.EnvVar, volumeMounts *[]corev1.VolumeMount, volumes *[]corev1.Volume, registryPasswordKey, secretName *string) {
+	const googlecredVolumeName = "gcrvol"
+	for _, v := range *volumes {
+		if v.Name == googlecredVolumeName {
+			return
+		}
+	}
+
```
Comment (simar7) [inline pkg/plugins/trivy/image.go:785]: To test something like this where the number of invocations that happen is what we're ultimately interested in, we could add a test where we keep track of invocations. Knowing how many times we expect `createEnvandVolumeForGcr` to get called can let us know if the logic is working as expected or if there's a bug.

In this example, with an early return in case of an existing mount, we should have less invocations than before introducing this change.

**Comment by simar7** [comment]
> @simar7 I remember you have a meticulous attitude toward testing, and I was thinking about how to add tests here.
> 
> A simple table-driven test for `createEnvAndVolumeForGcr` doesn’t make much sense in this context.
> 
> Once we resolve issues #2595 and #2769, we’ll be able to add a more meaningful test that covers multiple containers.

I left an idea https://github.com/aquasecurity/trivy-operator/pull/2801/files#r2591586352
