### PR TITLE
fix: get the data of the specified severity

### LINKED ISSUE #849: Trivy Severity settings not working
**What steps did you take and what happened:**
```
> helm install trivy-operator aqua/trivy-operator \
  --namespace trivy-system \
  --create-namespace \
  --set="trivy.severity=CRITICAL" \  
  --version 0.10.1

> kubectl get configauditreports --all-namespaces -o wide

NAMESPACE            NAME                                          SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW
trivy-system         service-trivy-operator                        Trivy     7s    0          0      0        0
kube-system          daemonset-kube-proxy                          Trivy     7s    0          2      4        10
kube-system          replicaset-metrics-server-69d9d66ff8          Trivy     7s    0          0      2        7
lens-metrics         statefulset-prometheus                        Trivy     7s    0          0      4        16
default              service-kubernetes                            Trivy     6s    0          0      0        1
lens-metrics         daemonset-node-exporter                       Trivy     6s    0          1      2        6
lens-metrics         replicaset-kube-state-metrics-77f89df94c      Trivy     6s    0          0      2        6
lens-metrics         service-prometheus                            Trivy     6s    0          0      0        0
kube-system          daemonset-kube-router                         Trivy     5s    0          2      8        24
trivy-system         replicaset-trivy-operator-59fc6d84d           Trivy     5s    0          0      1        7
lens-metrics         service-node-exporter                         Trivy     5s    0          0      0        0
local-path-storage   replicaset-local-path-provisioner-bc7cb895b   Trivy     4s    0          0      2        10
lens-metrics         service-kube-state-metrics                    Trivy     4s    0          0      0        0
ldk-webhooks         replicaset-dns-config-mutator-b59cddc47       Trivy     4s    0          0      0        2
kube-system          service-kube-dns                              Trivy     3s    0          0      1        0
kube-system          replicaset-coredns-5d5b5b96f9                 Trivy     3s    0          0      3        5
ldk-webhooks         service-dns-config-mutator                    Trivy     3s    0          0      0        0
kube-system          service-metrics-server                        Trivy     2s    0          0      1        0


> kubectl describe configmaps trivy-operator-trivy-config --namespace trivy-system


Name:         trivy-operator-trivy-config
Namespace:    trivy-system
Labels:       app.kubernetes.io/instance=trivy-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=trivy-operator
              app.kubernetes.io/version=0.10.1
              helm.sh/chart=trivy-operator-0.10.1
Annotations:  meta.helm.sh/release-name: trivy-operator
              meta.helm.sh/release-namespace: trivy-system

Data
====
trivy.command:
----
image
trivy.dbRepositoryInsecure:
----
false
trivy.repository:
----
ghcr.io/aquasecurity/trivy
trivy.resources.requests.cpu:
----
100m
trivy.additionalVulnerabilityReportFields:
----

trivy.mode:
----
Standalone
trivy.severity:
----
CRITICAL
trivy.tag:
----
0.35.0
trivy.useBuiltinRegoPolicies:
----
true
trivy.dbRepository:
----
ghcr.io/aquasecurity/trivy-db
trivy.resources.limits.memory:
----
500M
trivy.resources.requests.memory:
----
100M
trivy.timeout:
----
5m0s
trivy.resources.limits.cpu:
----
500m
trivy.slow:
----
true
trivy.supportedConfigAuditKinds:
----
Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota

BinaryData
====

Events:  <none>
```
[A clear and concise description of what the bug is, and what commands you ran.]

**What did you expect to happen:**

I expected to see only CRITICAL severity reports.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.10.1
- Kubernetes version (use `kubectl version`): v1.25.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 10.14

### PR DESCRIPTION
**Pull request by fengshunli**
## Description

https://github.com/aquasecurity/trivy-operator/issues/849#event-8498354536

## Related issues
- Close #849

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by chen-keinan — CHANGES_REQUESTED** [review]

**Comment by chen-keinan** [comment]
@fengshunli lgtm,  I have added one comment and also please rebase you branch with upstream

**Comment by fengshunli** [comment]
done

File: pkg/policy/policy.go [hunk 1]
```diff
@@ -236,6 +238,14 @@ func (r *Policies) GetResultID(result scan.Result) string {
 	return id
 }
 
+func (r *Policies) HasSeverity(severity severity.Severity) bool {
```
Comment (chen-keinan) [inline pkg/policy/policy.go:241]: probably better to change the param name to `resultSeverity` to avoid conflict with package name
```suggestion
func (r *Policies) HasSeverity(resultSeverity severity.Severity severity.Severity) bool {
```

**Review by chen-keinan — CHANGES_REQUESTED** [review]

**Comment by chen-keinan** [comment]
@fengshunli added one comment for lint issue

File: pkg/policy/policy.go (hunk 1 above)
Comment (fengshunli) [reply pkg/policy/policy.go]: done

**Comment by chen-keinan** [comment]
@fengshunli lgtm 🚀

**Review by chen-keinan — APPROVED** [review]
