### PR TITLE
fix: update policies not trigger rescan after operator startup

### LINKED ISSUE #351: update policies configmap after startup do not trigger rescan
**What steps did you take and what happened:**
 - start trivy-operator without empty configAudit policies config map
 - useBuiltInPolicies param is switch off
 -  update policies configmap (add policies)

Expected : old resources should be rescan with configAudit  new policies
Actual : old resource are not scanned

### PR DESCRIPTION
**Pull request by chen-keinan**
Signed-off-by: chenk <hen.keinan@gmail.com>

## Description
update policies not trigger rescan after operator startup

## Related issues
- Close #351 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ x I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).

### CODE REVIEW

File: pkg/configauditreport/controller/controller.go [hunk 1]
```diff
@@ -222,8 +222,16 @@ func (r *ResourceController) reconcileResource(resourceKind kube.Kind) reconcile
 		}
 
 		// Skip processing if there are no policies applicable to the resource
-
-		applicable, reason, err := policies.Applicable(resource, r.RbacAssessmentScannerEnabled)
+		suppoerted, err := policies.SupportedKind(resource, r.RbacAssessmentScannerEnabled)
```
Comment (erikgb) [inline pkg/configauditreport/controller/controller.go:225]:
```suggestion
		supported, err := policies.SupportedKind(resource, r.RbacAssessmentScannerEnabled)
```

**Review by josedonizetti — APPROVED** [review]
