### PR TITLE
fix: sync stdout buffer to file

### LINKED ISSUE #1792: Unexpected EOF log and vulnerability report no data
**What steps did you take and what happened:**

Hi,

We are facing issue the **vulnerability report no data** and log file contains **Unexpected EOF**

```
{"level":"error","ts":"2024-01-22T02:24:27Z","msg":"Reconciler error","controller":"job","controllerGroup":"batch","controllerKind":"Job","Job":{"name":"scan-vulnerabilityreport-59cb6b98d4","namespace":"trivy-system"},"namespace":"trivy-system","name":"scan-vulnerabilityreport-59cb6b98d4","reconcileID":"054a1f46-d3f3-43a0-a5a5-c8abb278627b","error":"unexpected EOF","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

value file:
```
operator:
  # scanJobsConcurrentLimit the maximum number of scan jobs create by the operator
  scanJobsConcurrentLimit: 1

  # -- scanJobTimeout the length of time to wait before giving up on a scan job
  scanJobTimeout: 20m
  
  # -- infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: false

  # -- controllerCacheSyncTimeout the duration to wait for controller resources cache sync (default: 5m).
  controllerCacheSyncTimeout: "10m"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

resources:
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 15m
    memory: 250Mi

trivyOperator:
  # -- scanJobPodTemplateContainerSecurityContext SecurityContext the user wants the scanner and node collector containers (and their
  # initContainers) to be amended with.
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    # -- For filesystem scanning, Trivy needs to run as the root user
    runAsUser: 0

trivy:
  # -- slow this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint
  slow: false

  # -- timeout is the duration to wait for scan completion.
  timeout: "20m0s"

  # -- command. One of `image`, `filesystem` or `rootfs` scanning, depending on the target type required for the scan.
  # For 'filesystem' and `rootfs` scanning, ensure that the `trivyOperator.scanJobPodTemplateContainerSecurityContext` is configured
  # to run as the root user (runAsUser = 0).
  command: filesystem
  
  # -- resources resource requests and limits for scan job containers
  resources:
    requests:
      cpu: 100m
      memory: 1000M
      # ephemeralStorage: "2Gi"
    limits:
      cpu: 500m
      memory: 2000M
      # ephemeralStorage: "2Gi"
```

Any suggestion to resolve this issue would be very much appreciated!

Thanks!

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.20.1
- Kubernetes version (use `kubectl version`): 1.25
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

### PR DESCRIPTION
**Pull request by daanschipper**
## Description
The trivy command is completed and as it is the main process the entire container is stopped before the stdout buffer is cleared, resulting in malformed output.

This patch has been running for over a month and I have not experienced any lingering scan vulnerability jobs which could not be removed by the operator anymore. Used `kube_job_complete{namespace="trivy-system", condition="true", job_name=~"scan-vulnerabilityreport-[0-9a-f]+"}` to alert for scan jobs with malformed output.

I did refactor the `getCommandAndArgs` function to deduplicate the logic for compressed and not compressed mode, it was essentially the same. Also ensured the options are in alphabetic order.

## Related issues
- Close #1792.

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [x] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed). Not applicable.
- [x] I've added usage information (if the PR introduces new options). Not applicable.
- [x] I've included a "before" and "after" example to the description (if the PR is a user interface change).  Not applicable.

### CODE REVIEW

**Comment by daanschipper** [comment]
Also updated the `*-expected-scan.yaml` files for the envtest.

**Comment by daanschipper** [comment]
@chen-keinan could you trigger the workflow again? :pray:

**Comment by hsedr** [comment]
Are there any plans to merge these changes? We are also experiencing reconciliation errors with the trivy operator every now and then, because the scan job logs are truncated and therefore not decompressible.

best regards

**Comment by daanschipper** [comment]
@hsedr You can use `ghcr.io/daanschipper/trivy-operator:0.22.0-sync0.0.3`, that has the above changes and some dependency upgrades.

**Comment by hsedr** [comment]
@daanschipper Thanks for your contribution! I'll take it into consideration. But I think it would be best if this fix ends up in this repository.

**Comment by daanschipper** [comment]
Agreed, resolved the merge conflict. This PR received no attention for months, therefore I opted to publish my changes and use that.

**Comment by afdesk** [comment]
@daanschipper thanks for the contribution! I'll take a look at this PR

File: pkg/plugins/trivy/image.go [hunk 1]
```diff
@@ -588,84 +588,85 @@ func getCommandAndArgs(ctx trivyoperator.PluginContext, mode Mode, imageRef, tri
...
+	pkgList := getPkgList(ctx)
+	if pkgList != "" {
+		args = append(args, pkgList)
 	}
-	return []string{"/bin/sh"}, []string{"-c", fmt.Sprintf(`trivy image %s '%s' %s %s %s %s %s %s%s --cache-dir %s --quiet %s --format json %s> /tmp/scan/%s &&  bzip2 -c /tmp/scan/%s | base64`, slow, imageRef, scanners, getSecurityChecks(ctx), imageconfigSecretScannerFlag, vulnTypeFlag, skipUpdate, skipJavaDBUpdate, sbomSourcesFlag, cacheDir, getPkgList(ctx), serverUrlParms, resultFileName, resultFileName)}
+
+	// Return early when compressing logs is disabled.
+	compressLogs := trivyOperatorConfig.CompressLogs()
+	if !compressLogs {
+		return command, args
```
Comment (afdesk) [inline pkg/plugins/trivy/image.go:660]:
```suggestion
		return []string{"trivy"}, args
```

Comment (afdesk) [reply pkg/plugins/trivy/image.go:660]: there is only one using of `command`

**Comment by afdesk** [comment]
@daanschipper thanks for your work! Looks great! 
I left a really small comment to refactor this block.

Although there is a mixing refactoring and a fix (improvement with `sync`) in the same PR, there isn’t much logic involved here, so it’s fine.
@simar7 wdyt?

File: pkg/plugins/trivy/image.go (hunk 1 above)
Comment (daanschipper) [reply pkg/plugins/trivy/image.go:660]: There is another usage on line 664. If you still want `[]string{"trivy"}` instead I'm fine changing it though!

**Comment by simar7** [comment]
hi @daanschipper thanks for the PR. It lgtm, but just curious if we can assume the `sync` utility to be widely available on most machines? Otherwise we would risk breakage.

**Comment by daanschipper** [comment]
`sync` is a standard system call in the unix operating system, see https://linux.die.net/man/8/sync.

**Comment by daanschipper** [comment]
@simar7 can this be merged?

**Review by simar7 — APPROVED** [review]
