### PR TITLE
fix: parseImageRef tag absence issue when digest in imageRef 

### LINKED ISSUE #2411: Empty tag in all reports when deployed with digester
**What steps did you take and what happened:**

I've deployed trivy-opeator on cluster with k8s-digester. 
k8s-digester is a mutate webhook, it resolves tag and adds digest to every Deployment, StatefulSet or Pod. 

For example reference mirror.gcr.io/aquasec/trivy:0.58.0 will be replaced with:
mirror.gcr.io/aquasec/trivy:0.58.0@sha256:b88012e2a0a309d6a8a00463d4e63e5e513377fb74eccbc8f9b0f8f81940ebeb

https://github.com/google/k8s-digester

After deployment I found that most reports perform without tags. 

`
% kubectl get vulnerabilityreports.aquasecurity.github.io replicaset-vector-6479d4f44b-vector  -n vector -o yaml             
apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityReport
metadata:
  annotations:
    trivy-operator.aquasecurity.github.io/report-ttl: 24h0m0s
  creationTimestamp: "2025-01-31T11:56:18Z"
  generation: 1
  labels:
    resource-spec-hash: 96d854ff9
    trivy-operator.container.name: vector
    trivy-operator.resource.kind: ReplicaSet
    trivy-operator.resource.name: vector-6479d4f44b
    trivy-operator.resource.namespace: vector
  name: replicaset-vector-6479d4f44b-vector
  namespace: vector
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: ReplicaSet
    name: vector-6479d4f44b
    uid: 807c20a4-3e63-49fc-99ae-06a4263239e7
  resourceVersion: "173100373"
  uid: 66160640-83b4-43a8-86a4-e4be738ef6b0
report:
  artifact:
    digest: sha256:131485defae3fc07fa20cf9dda85bb3056e8d0d475a8aa387c6d6417eca0223b
    repository: timberio/vector
  os:
    family: debian
    name: "12.8"
  registry:
    server: index.docker.io
  scanner:
`

`
% kubectl get pod -n vector vector-6479d4f44b-ccrrz -o yaml | grep image
    image: timberio/vector:0.43.1-distroless-libc@sha256:131485defae3fc07fa20cf9dda85bb3056e8d0d475a8aa387c6d6417eca0223b
    imagePullPolicy: IfNotPresent
    image: sha256:9f544504e5b7b1aa782b14cc84efe37a58fb225dc345a0bac4e4fea098fc9e37
    imageID: docker.io/timberio/vector@sha256:131485defae3fc07fa20cf9dda85bb3056e8d0d475a8aa387c6d6417eca0223b
`

**What did you expect to happen:**

I expect recieve all reports with tags if tags was provided in deployments. (In this particular example tag should be: 0.43.1-distroless-libc)

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): v0.23.0
- Kubernetes version (use `kubectl version`): 
Client Version: v1.30.2; 
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3;
Server Version: v1.30.8-gke.1128000

- OS (macOS Sonoma 14.4.1 (23E224)):

### PR DESCRIPTION
**Pull request by danchenko-dmitry**
I've changed behaviour of parseImageRef func.
before:
In case when imageRef -> "my-private-repo.company.com/my-app:some-tag@sha256:1420cefd4b20014b3361951c22593de6e9a2476bbbadd1759464eab5bfc0d34f"
It returns empty tag in Artifact.Tag;

after:
In new version this behaviour fixed and it returns tag instead empty string.
you can see it it "15. private registry image ref tag & with digest" test.

Related issues
Close https://github.com/aquasecurity/trivy-operator/issues/2411

## Checklist
- [X] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [Not need] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [Not need] I've added usage information (if the PR introduces new options)
- [X] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by danchenko-dmitry** [comment]
@afdesk This is continue of our discussion of way to handle issue. https://github.com/aquasecurity/trivy-operator/pull/2412
I've added tests and add your changes to code. It works fine.
So we can use it PR instead 2412

File: pkg/plugins/trivy/plugin.go [hunk 1]
```diff
@@ -229,6 +229,12 @@ func (p *plugin) parseImageRef(imageRef, imageDigest string) (v1alpha1.Registry,
 		artifact.Tag = t.TagStr()
 	case containerimage.Digest:
 		artifact.Digest = t.DigestStr()
+
+		var artifactDigest string
+		if refParts := strings.Split(imageRef, "@");len(refParts)==2 {
+			artifactDigest = refParts[1]
+		}
```
Comment (afdesk) [inline pkg/plugins/trivy/plugin.go:236]: it looks like we don't need this split, because `artifactDigest` is already exist in `artifact.Digest = t.DigestStr()`.

File: pkg/plugins/trivy/plugin.go [hunk 2]
```diff
@@ -155,7 +155,7 @@ func (p *plugin) ParseReportData(ctx trivyoperator.PluginContext, imageRef strin
 
 	imageDigest := p.getImageDigest(reports)
 
-	registry, artifact, err := p.parseImageRef(imageRef, imageDigest)
+	registry, artifact, err := ParseImageRef(imageRef, imageDigest)
```
Comment (afdesk) [inline pkg/plugins/trivy/plugin.go:158]: why do you want to mark this method as `public`?

**Review by afdesk — CHANGES_REQUESTED** [review]

**Comment by afdesk** [comment]
@danchenko-dmitry thanks for efforts! I believe we'll follow up this update soon

could you move the descrition from #2412 too?

File: pkg/plugins/trivy/plugin.go (hunk 2 above)
Comment (danchenko-dmitry) [reply pkg/plugins/trivy/plugin.go:158]: > why do you want to mark this method as `public`?

because I can't call it from tests ... plugin_test.go has a different package name so it is another golang package.

File: pkg/plugins/trivy/plugin.go (hunk 1 above)
Comment (danchenko-dmitry) [reply pkg/plugins/trivy/plugin.go]: Ok, agree. Removed this code.

**Comment by danchenko-dmitry** [comment]
> @danchenko-dmitry thanks for efforts! I believe we'll follow up this update soon
> 
> could you move the descrition from #2412 too?

Done.

**Review by afdesk — APPROVED** [review]
@danchenko-dmitry thanks! 

@simar7 wdyt?

**Comment by danchenko-dmitry** [comment]
Hi guys! As I see this PR has already been forgotten. :-)
Please do not forget it, we need that functionality ...
@simar7 @afdesk

File: pkg/plugins/trivy/plugin_test.go [hunk 3]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+		// args:
+		imageRef string
+		imageID  string
+		// result:
+		registry v1alpha1.Registry
+		artifact v1alpha1.Artifact
+		err      error
+	}{
+		{
+			name:     "1. short image ref with latest tag",
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7645]: you can eliminate numbering in tests
```suggestion
			name:     "short image ref with latest tag",
```

File: pkg/plugins/trivy/plugin_test.go [hunk 4]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+			},
+			artifact: v1alpha1.Artifact{
+				Repository: "library/nginx",
+				Digest:     "sha256:2bc57c6bcb194869d18676e003dfed47b87d257fce49667557fb8eb1f324d5d6",
+				Tag:        "v1.3.4",
+			},
+			err: nil,
+		},
+		{
+			name:     "2. short repo with default lib with latest tag",
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7659]: ditto

File: pkg/plugins/trivy/plugin_test.go [hunk 5]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+			},
+			artifact: v1alpha1.Artifact{
+				Repository: "library/nginx",
+				Digest:     "sha256:2bc57c6bcb194869d18676e003dfed47b87d257fce49667557fb8eb1f324d5d6",
+				Tag:        "v.4.5.6",
+			},
+			err: nil,
+		},
+		{
+			name:     "3. well known image without tag & digest",
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7673]: ditto

File: pkg/plugins/trivy/plugin_test.go [hunk 6]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+			imageID:  "sha256:2bc57c6bcb194869d18676e003dfed47b87d257fce49667557fb8eb1f324d5d6",
+			registry: v1alpha1.Registry{
+				Server: "index.docker.io",
+			},
+			artifact: v1alpha1.Artifact{
+				Repository: "library/nginx",
+				Digest:     "sha256:2bc57c6bcb194869d18676e003dfed47b87d257fce49667557fb8eb1f324d5d6",
+				Tag:        "v1.3.4",
+			},
+			err: nil,
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7656]: In Go the default for error is `nil`. So we can omit this.
```suggestion
```

Comment (simar7) [reply pkg/plugins/trivy/plugin_test.go:7656]: ditto for all the others

File: pkg/plugins/trivy/plugin_test.go [hunk 7]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+		},
+	}
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			registry, artifact, err := trivy.ParseImageRef(tc.imageRef, tc.imageID)
+			assert.Equal(t, tc.registry, registry)
+			assert.Equal(t, tc.artifact, artifact)
+			if tc.err != nil {
+				require.Errorf(t, err, "expected: %v", tc.err)
+			}
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7785]: nit:
```suggestion
			registry, artifact, err := trivy.ParseImageRef(tc.imageRef, tc.imageID)
			if tc.err != nil {
				require.Errorf(t, err, "expected: %v", tc.err)
			}
			assert.Equal(t, tc.registry, registry)
			assert.Equal(t, tc.artifact, artifact)

```

File: pkg/plugins/trivy/plugin_test.go [hunk 8]
```diff
@@ -7629,3 +7629,160 @@ func TestExcludeImages(t *testing.T) {
...
+func TestParseImageRef(t *testing.T) {
+	testCases := []struct {
+		name string
+		// args:
+		imageRef string
+		imageID  string
+		// result:
+		registry v1alpha1.Registry
+		artifact v1alpha1.Artifact
+		err      error
```
Comment (simar7) [inline pkg/plugins/trivy/plugin_test.go:7642]: nit: 

```suggestion
		name string
		inputImageRef string
		inputImageID  string
		expectedRegistry v1alpha1.Registry
		expectedArtifact v1alpha1.Artifact
		err      error
```

**Review by simar7 — CHANGES_REQUESTED** [review]
thanks @danchenko-dmitry for your PR, I just left some small styling comments.

**Review by simar7 — APPROVED** [review]
