### PR TITLE
fix: dbRepositoryInsecure param always return true

### LINKED ISSUE #245: env TRIVY_INSECURE always set to TRUE in the job manifest
**What steps did you take and what happened:**

After inspecting job manisfest, it looks like env   TRIVY_INSECURE is always set to True,
even though trivy-operator-trivy-config configmap contains :
 
  trivy.dbRepositoryInsecure: "false"
  trivy.serverInsecure: "false"

**What did you expect to happen:**

 TRIVY_INSECURE set to False  when   trivy.dbRepositoryInsecure: "false" and trivy.serverInsecure: "false"

**Anything else you would like to add:**

I may have missed a setting ? could you help please ?

**Environment:**

- Trivy-Operator version (use `trivy-operator version`):
```
{"level":"info","ts":1657004238.8778963,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.1.0","Commit":"63a98e9d08e8dc5fc97c57e5c07fbafbe32cf42f","Date":"2022-06-30T11:25:27Z","Executable":""}}
{"level":"info","ts":1657004238.8782058,"logger":"operator","msg":"Resolved install mode","install mode":"AllNamespaces","operator namespace":"trivy-system","target namespaces":[],"exclude namespaces":"kube-system,trivy-system"}
```

- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9"
```

### PR DESCRIPTION
**Pull request by chen-keinan**
Signed-off-by: chenk <hen.keinan@gmail.com>

## Description
dbRepositoryInsecure param always return true

## Related issues
- Close #245 

## Checklist
- [x] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [x] I've added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

File: pkg/plugin/trivy/plugin.go [hunk 1]
```diff
@@ -145,8 +145,15 @@ func (c Config) GetServerInsecure() bool {
 }
 
 func (c Config) GetDBRepositoryInsecure() bool {
-	_, ok := c.Data[keyTrivyDBRepositoryInsecure]
-	return ok
+	val, ok := c.Data[keyTrivyDBRepositoryInsecure]
+	if !ok {
+		return false
+	}
+	boolVal, err := strconv.ParseBool(val)
```
Comment (josedonizetti) [inline pkg/plugin/trivy/plugin.go:152]: we could remove the `if` if we prefer, cos `boolVal` will be false in case of an error.
```suggestion
	boolVal, _ := strconv.ParseBool(val)
	return boolVal
```

Comment (chen-keinan) [reply pkg/plugin/trivy/plugin.go:152]: ok , I hope it will not fail lint
