### PR TITLE
fix(misconfig): ordering policies for hash

### LINKED ISSUE #2518: Trivy operator audit reports are generated every second
We are experiencing a reconciliation loop where resourcecontroller logs "Checking whether configuration audit report exists" and reconciler.ttlreport logs "RequeueAfter" with a ~22h durationToTTLExpiration every second for pods and ReplicaSets (e.g., pod-nginxlatest, replicaset-aqua-server-console-7c8684778f). Resources are Running, and config audit reports are constantly being generated (OPERATOR_CONFIG_AUDIT_SCANNER_ENABLED active, ScannerReportTTL implied ~24h). No ERROR logs appear at DEBUG level. This loop could potentially impact performance. Our hunch is that hasReport in ResourceController might not recognize existing reports or TTLReportReconciler is requeuing prematurely, ignoring the TTL duration. Logs and env vars attached.

Example:
2025-04-06T10:39:16Z	DEBUG	reconciler.ttlreport	RequeueAfter	{"report": {"name":"replicaset-aqua-server-console-7c8684778f","namespace":"aqua"}, "durationToTTLExpiration": "23h59m49.953891129s"}

### PR DESCRIPTION
**Pull request by afdesk**
## Related issues
- Close #2518 

## Checklist
- [ ] I've read the [guidelines for contributing](https://github.com/aquasecurity/trivy-operator/blob/main/CONTRIBUTING.md) to this repository.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy-operator/tree/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by simar7** [comment]
@afdesk in my benchmarks measuring the performance of adding sorting, there isn't any noticeable hit.

```diff
  benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/aquasecurity/trivy-operator/pkg/policy/bench
cpu: Apple M1 Pro
                 │   old.txt   │            new.txt             │
                 │   sec/op    │   sec/op     vs base           │
Policies_Hash-10   884.6n ± 1%   906.5n ± 3%  ~ (p=0.150 n=100)

                 │  old.txt   │             new.txt             │
                 │    B/op    │    B/op     vs base             │
Policies_Hash-10   673.0 ± 0%   673.0 ± 0%  ~ (p=1.000 n=100) ¹
¹ all samples are equal

                 │  old.txt   │             new.txt             │
                 │ allocs/op  │ allocs/op   vs base             │
Policies_Hash-10   18.00 ± 0%   18.00 ± 0%  ~ (p=1.000 n=100) ¹
¹ all samples are equal

```

**Comment by simar7** [comment]
Here's the benchmark: https://gist.github.com/simar7/256e4473f6f868169297c3169c59ead3

File: pkg/policy/policy.go [hunk 1]
```diff
@@ -123,6 +124,11 @@ func (p *Policies) Hash(kind string) (string, error) {
 	if err != nil {
 		return "", fmt.Errorf("failed to load built-in / external policies: %s: %w", kind, err)
 	}
+	/*
+		if len(policies) == 0 {
+			return "", errors.New("no policies found")
+		}
```
Comment (afdesk) [inline pkg/policy/policy.go:130]: there is some problem with this check or integration test for it

Comment (simar7) [reply pkg/policy/policy.go:130]: Hmm interesting - does it fail locally for you? In my local setup I've run it a few times without any failures.

Comment (simar7) [reply pkg/policy/policy.go]: I removed it for now based on our discussion https://github.com/aquasecurity/trivy-operator/pull/2520/commits/4792da8af292525824162cb75d18b95ab79b5377

**Review by simar7 — APPROVED** [review]
